version: '3.7'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: 3bWmVlVgaAxJYykHywQf
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: 3bWmVlVgaAxJYykHywQf
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      LOGSTASH_INTERNAL_PASSWORD: ZNcYdSLZqdj9GRrhyHJ3
    networks:
      - elk
    depends_on:
      - elasticsearch
  filebeat:
    container_name: filebeat
    hostname: filebeat
    #user: root
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
        #environment:   
        # ELASTICSEARCH_HOSTS: :9200
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
        #command: filebeat -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=SyPCS4FgpXIAogupnO7e --strict.perms=false   
        #command: filebeat -e
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
